#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Termostat2

EXTRA_COMPONENT_DIRS = ${TERMOSTAT_DIR}/extras/ds18b20

include $(IDF_PATH)/make/project.mk
